"""interaction affected entity

Revision ID: 5abb1ff85633
Revises: 5c5c692ecb32
Create Date: 2026-09-29 11:54:47.632259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abb1ff85633'
down_revision: Union[str, Sequence[str], None] = '5c5c692ecb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('affected_entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interactions', 'entities', ['affected_entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'affected_entity_id')
    # ### end Alembic commands ###
