"""review audit trail

Revision ID: 5c5c692ecb32
Revises: 8cc739bfb36a
Create Date: 2026-09-29 11:39:51.685916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5c692ecb32'
down_revision: Union[str, Sequence[str], None] = '8cc739bfb36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('reviewed_by', sa.String(length=128), nullable=True))
    op.add_column('interactions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interactions', sa.Column('review_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'review_note')
    op.drop_column('interactions', 'reviewed_at')
    op.drop_column('interactions', 'reviewed_by')
    # ### end Alembic commands ###
