"""initial schema

Revision ID: 8cc739bfb36a
Revises: 
Create Date: 2026-08-29 21:40:40.201803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc739bfb36a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('NUTRIENT', 'HERBAL', 'DRUG', 'OTHER', name='entitykind'), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('rxcui', sa.String(length=32), nullable=True),
    sa.Column('unii', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'canonical_name', name='uq_entity_kind_name')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entity_rxcui', ['rxcui'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarantined_triples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_alias_entity_norm')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_alias_normalized', ['normalized_alias'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_a_id', sa.Integer(), nullable=False),
    sa.Column('entity_b_id', sa.Integer(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('CONTRAINDICATED', 'MAJOR', 'MODERATE', 'MINOR', 'THEORETICAL', name='severity'), nullable=False),
    sa.Column('evidence_grade', sa.Enum('A', 'B', 'C', 'D', name='evidencegrade'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'PUBLISHED', 'REJECTED', name='interactionstatus'), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_a_id', 'entity_b_id', name='uq_interaction_pair')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index('ix_interaction_a', ['entity_a_id'], unique=False)
        batch_op.create_index('ix_interaction_b', ['entity_b_id'], unique=False)

    op.create_table('timing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_a_id', sa.Integer(), nullable=False),
    sa.Column('entity_b_id', sa.Integer(), nullable=False),
    sa.Column('separation_hours', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_a_id', 'entity_b_id', name='uq_timing_pair')
    )
    op.create_table('upper_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('population', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'population', name='uq_ul_entity_population')
    )
    op.create_table('conflict_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('existing_value', sa.String(length=255), nullable=False),
    sa.Column('incoming_value', sa.String(length=255), nullable=False),
    sa.Column('incoming_source_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('span', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('conflict_records')
    op.drop_table('upper_limits')
    op.drop_table('timing_rules')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_interaction_b')
        batch_op.drop_index('ix_interaction_a')

    op.drop_table('interactions')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index('ix_alias_normalized')

    op.drop_table('entity_aliases')
    op.drop_table('quarantined_triples')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_rxcui')

    op.drop_table('entities')
    # ### end Alembic commands ###
