"""drug classes

Revision ID: d30db2cfeead
Revises: 5abb1ff85633
Create Date: 2026-09-29 12:42:51.603088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30db2cfeead'
down_revision: Union[str, Sequence[str], None] = '5abb1ff85633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate cannot see new enum members. SQLAlchemy stores the member NAME.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE entitykind ADD VALUE IF NOT EXISTS 'CLASS'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'member_id', name='uq_class_member')
    )
    op.create_index('ix_class_member_member', 'class_memberships', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_class_member_member', table_name='class_memberships')
    op.drop_table('class_memberships')
    # ### end Alembic commands ###
    # Postgres cannot drop an enum value; CLASS stays in the type, unused.
